baseurl = "https://zwilder.github.io/"
languageCode = "en"
title = "WSL Programming Blog"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/zwilder\">Zach Wilder</a> 2017"
disqusShortname = "wsl-programming-blog"
# googleAnalytics = ""
publishDir = "build"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "cpp"]

[[params.social]]
url = "https://github.com/zwilder"
fa_icon = "fa-github"

[[params.social]]
#url = ""
# fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
