baseurl = "/"
languageCode = "en-us"
title = "WSL Programming Blog"
theme = "hugo-xmin"
googleAnalytics = "UA-121310852-1"
disqusShortname = "wsl-programming-blog"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.bak$", "\\.un~$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
publishDir = "../"
pygmentsStyle = "solarized-dark256"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "rss"
    url = "/index.xml"

[params]
    description = "A website built through Hugo by a guy who doesn't exactly know what he's doing..."
    footer = "&copy; <a href=\"https://github.com/zwilder\">Zach Wilder</a> 2018"
